# Generated by Django 3.2.4 on 2021-07-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerInfo',
            fields=[
                ('container_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('container_status', models.CharField(default='stop', max_length=10)),
                ('volumes_path', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
